all:
  hosts:
    r1:
      ansible_host: 192.168.1.104
      ansible_user: admin
      ansible_password: admin
      ansible_connection: network_cli
      ansible_network_os: community.routeros.routeros
    r2:
      ansible_host: 192.168.1.108
      ansible_user: admin
      ansible_password: admin
      ansible_connection: network_cli
      ansible_network_os: community.routeros.routeros
